source 'http://rubygems.org'
gem 'rails', '3.0.0.beta3'

source 'http://gems.github.com'
gem 'mbleigh-subdomain-fu', :require => 'subdomain-fu'
gem 'authlogic'
gem 'authlogic-oid', :require => 'authlogic_openid'
gem 'ruby-openid', :require => 'openid'
source 'http://gems.github.com'
gem 'mdarby-restful_acl', :require => 'restful_acl_controller'
source 'http://gems.github.com'
gem 'peteonrails-vote_fu', :require => 'vote_fu'
gem 'json'
gem 'ym4r'
gem 'sunlight'
gem 'geokit'
source 'http://gems.github.com'
gem 'mislav-will_paginate', '~> 2.3.11', :require => 'will_paginate'
